# Generated by Django 2.1.3 on 2019-05-05 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '互粉关系',
                'db_table': 'userfans',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uiid', models.IntegerField(primary_key=True, serialize=False, verbose_name='博主ID')),
                ('title', models.CharField(max_length=100, verbose_name='个人主站标题')),
                ('site', models.CharField(max_length=100, unique=True, verbose_name='个人主站前缀')),
                ('theme', models.CharField(max_length=100, verbose_name='个人主站主题')),
            ],
            options={
                'verbose_name_plural': '个人主站信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='赞数'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default='1025-02-23', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='suosuo', max_length=36, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterUniqueTogether(
            name='self_class',
            unique_together={('user', 'caption')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'caption')},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='repository.User'),
        ),
        migrations.AddField(
            model_name='userfans',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_user', to='repository.User', verbose_name='粉丝'),
        ),
        migrations.AddField(
            model_name='userfans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_user', to='repository.User', verbose_name='博主'),
        ),
        migrations.AlterUniqueTogether(
            name='userfans',
            unique_together={('user', 'follower')},
        ),
    ]
