# Generated by Django 2.1.3 on 2019-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190505_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
