# Generated by Django 2.1.3 on 2019-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20190505_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
