# Generated by Django 2.1.3 on 2019-04-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='课程名')),
                ('hours', models.IntegerField(verbose_name='课时')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.BooleanField(choices=[(0, False), (1, True)], verbose_name='性别')),
                ('born_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('graduate', models.CharField(max_length=100, verbose_name='毕业院校')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiwei.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='stus',
            field=models.ManyToManyField(to='shiwei.Student'),
        ),
    ]
