/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2019-01-01 02:38:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/de_jQuery_3_3_1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- favicon.ico 图标用于收藏夹图标和浏览器标签上的显示，\r\n");
      out.write("如果不设置，浏览器会请求网站根目录的这个图标，如果网站根目录也没有这图标会产生 404。\r\n");
      out.write("出于优化的考虑，要么就有这个图标，要么就禁止产生这个请求。\r\n");
      out.write("在做 H5 混合应用的时候，不希望产生 favicon.ico 的请求。\r\n");
      out.write("可以在页面的 <head> 区域，加上如下代码实现屏蔽： -->\r\n");
      out.write("<link rel=\"icon\" href=\"data:image/ico;base64,aWNv\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/*      $(document).ready(function(){\r\n");
      out.write("    \t$(\"#testJson\").click(function(){\r\n");
      out.write("    \t\t//通过 ajax 请求  Springmvc \r\n");
      out.write("\t\t\t$.post(\r\n");
      out.write("\t\t\t\t\t\"SpringMVC/testJson\", // 服务器地址//{\"name\":\"za\"},//{\"name\":\"za\",\"age\":\"23\"}\r\n");
      out.write("\t\t\t        function(result){   //服务端 处理完毕后的 回调函数,返回 List<>\r\n");
      out.write("\t\t\t\t\t\t// eval(result);\r\n");
      out.write("\t\t\t          //for(int i=0;i<result){\r\n");
      out.write("\t\t\t        \t  alert(124578);\r\n");
      out.write("\t\t\t          });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("  \r\n");
      out.write("\t}); \r\n");
      out.write("\t */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t // 老师写的 \r\n");
      out.write("\t $(document).ready(function() {\r\n");
      out.write("\t      $(\"#testJson\").click(function(){\r\n");
      out.write("\t    var url = \"SpringMVC/testJson\";\r\n");
      out.write("\t    var args = {};\r\n");
      out.write("\t    $.post(url, args, function(result){\r\n");
      out.write("\t     for(var i = 0; i < result.length; i++){\r\n");
      out.write("\t                       //以JSON的形式处理响应结果\r\n");
      out.write("\t      var stuId = result[i].id;                 \r\n");
      out.write("\t      var stuName = result[i].name;\r\n");
      out.write("\t      var stuAge = result[i].age;\r\n");
      out.write("\t      alert(\"编号：\"+ stuId + \"姓名\" + stuName + \",年龄\" + stuAge);\r\n");
      out.write("\t     }\r\n");
      out.write("\t    });\r\n");
      out.write("\t   });\r\n");
      out.write("\t   }); \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"button\" value=\"testJson\" id=\"testJson\"><br>\r\n");
      out.write("\t<a href=\"SpringMVC/welcome/shiwei\"> first springMVC - welcome</a>\r\n");
      out.write("\t<!--   <form action=\"SpringMVC/welcome\" method=\"post\">\r\n");
      out.write(" name:<input name=\"name\"> \r\n");
      out.write(" age <input >\r\n");
      out.write("       <input type=\"submit\" value=\"Post提交\">\r\n");
      out.write("  </form> -->\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"SpringMVC/testRest/1243\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"增加\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"SpringMVC/testRest/1243\" method=\"get\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"查询\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"SpringMVC/testRest/666666\" method=\"post\">\r\n");
      out.write("\t <input type=\"hidden\" name=\"_method\" value=\"DELETE\" /> \r\n");
      out.write("\t\t<input type=\"submit\" value=\"删除\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"SpringMVC/testRest/1243\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"_method\" value=\"PUT\" />\r\n");
      out.write("\t\t <input  type=\"submit\" value=\"改变\">\r\n");
      out.write("\t</form> \r\n");
      out.write("\t------------------------<br/>\r\n");
      out.write("\t<form action=\"SpringMVC/testParam\" method=\"get\">\r\n");
      out.write("\t\t<input name=\"uname\" type=\"text\">\r\n");
      out.write("\t\t<!-- <input name=\"uage\" type=\"text\"> -->\r\n");
      out.write("\t\t<input type=\"submit\" value=\"查值\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"SpringMVC/testRequestHeader\" method=\"get\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"获取头信息\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t<form action=\"SpringMVC/testCookieValue\" method=\"get\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"获取Cookie\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--在这里体现了 Spring MVC 的强大之处，自动将值对号入座存入对象的属性当中去  -->\r\n");
      out.write("\t<form action=\"SpringMVC/testObjectProperties\" method=\"get\">\r\n");
      out.write("\t     age:<input name=\"age\" type=\"text\"><br>\r\n");
      out.write("\t     name:<input name=\"name\" type=\"text\"><br>\r\n");
      out.write("\t     homeAddress:<input name=\"address.homeAddress\" type=\"text\"><br>\r\n");
      out.write("\t     schoolAddress:<input name=\"address.schoolAddress\" type=\"text\"><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"获取Cookie\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"SpringMVC/testServletAPI\" method=\"get\">\r\n");
      out.write("\t\t<input name=\"uname\" type=\"text\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"HttpServletRequest\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write(" <a href=\"SpringMVC/testModelAndView\" >ModelAndView</a><br>\r\n");
      out.write(" <a href=\"SpringMVC/testModelMap\" >ModelMap</a><br>\r\n");
      out.write(" <a href=\"SpringMVC/testMap\" >Map</a><br>\r\n");
      out.write(" <a href=\"SpringMVC/testModel\" >Model</a><br>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t<form action=\"SpringMVC/testModelAttribute\" method=\"get\">\r\n");
      out.write("         \t编号 :<input name=\"age\" type=\"hidden\" value=\"100\"><br>\r\n");
      out.write("\t     \t姓名 :<input name=\"name\" type=\"text\"><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"@ModelAttribute\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"SpringMVC/direct\">direct</a><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"SpringMVC/forward\">forward</a><br>\r\n");
      out.write("\t\r\n");
      out.write("    <a href=\"SpringMVC/redirect\">redirect</a><br>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"wang.jsp\">传统 的  A  标签</a>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <!-- 类型转换器  -->\r\n");
      out.write("     <form action=\"SpringMVC/testConverter\" method=\"get\">\r\n");
      out.write("         \t学生信息：<input name=\"studentInfo\" type=\"text\"><br>\r\n");
      out.write("\t\t     <input type=\"submit\" value=\"学生信息的转换\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!--数据 格式化  Date   -->\r\n");
      out.write("\t<form action=\"SpringMVC/dateFormatting\" method=\"get\">\r\n");
      out.write("         \t编号 :<input name=\"id\" type=\"text\"><br>\r\n");
      out.write("\t     \t姓名 :<input name=\"name\" type=\"text\"><br>\r\n");
      out.write("\t\t\t出生日期:<input name=\"birthday\" type=\"text\"><br>  \r\n");
      out.write("\t\t\tEmail: <input name=\"email\" type=\"text\"><br>  \r\n");
      out.write("\t\t<input type=\"submit\" value=\"学生出生日期数据的格式化\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("      <br>\r\n");
      out.write("      <!-- SpringMVC 实现文件的 上传  \r\n");
      out.write("      注意点： 1.  必须是 Post  请求 \r\n");
      out.write("         2.  enctype=\"multipart/form-data\" -->\r\n");
      out.write("      <form action=\"SpringMVC/testMultipartResolver\"\r\n");
      out.write("         method=\"post\"  enctype=\"multipart/form-data\">\r\n");
      out.write("\t     \t<input type=\"file\" name=\"file\"><br>\r\n");
      out.write("\t     \t描述：<input name=\"desc\" type=\"text\"><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"上传\">\r\n");
      out.write("\t   </form><br>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"SpringMVC/testInterceptor\">拦截测试</a><br>\r\n");
      out.write("\r\n");
      out.write("   <a href=\"SecondMVC/One\">算数异常 </a><br>\r\n");
      out.write("   \r\n");
      out.write("   <a href=\"SecondMVC/Three\">数组越界 异常 </a><br>\r\n");
      out.write("   \r\n");
      out.write("   <a href=\"SpringMVC/testException\">其他类中的算数异常</a><br>\r\n");
      out.write("\r\n");
      out.write("     <a href=\"SecondMVC/defineExcetpion1\">自定义 异常类 </a><br>\r\n");
      out.write("     \r\n");
      out.write("     <a href=\"SecondMVC/defineExcetpion2?i=3\">自定义 异常 方法</a><br>\r\n");
      out.write("\r\n");
      out.write("   <a href=\"SecondMVC/SimpleMappingExceptionResolver\">配置异常类 </a>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
