# Generated by Django 2.1.3 on 2019-06-05 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190605_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级列表 '},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name_plural': '讲师上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name_plural': '客户跟踪记录表'},
        ),
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name_plural': '动态菜单表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学员表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name_plural': '学员学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='menus',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='菜单名'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_name',
            field=models.CharField(max_length=1024, verbose_name=' 菜单URL'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'absolute'), (1, 'dynamic')], default=0, verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Role', verbose_name='拥有角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联系统账户'),
        ),
    ]
