# Generated by Django 2.1.3 on 2019-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiwei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(upload_to='', verbose_name='图片地址'),
        ),
    ]
