# Generated by Django 2.1.3 on 2019-04-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiwei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='addr',
            field=models.CharField(max_length=50, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateTimeField(max_length=50, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='qq',
            field=models.BigIntegerField(verbose_name='腾讯QQ'),
        ),
    ]
